### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulahub-extensions#5]
## General description
Need to wrap [Logger from here](https://github.com/capsulajs/capsulahub-ui/tree/develop/src/components/logger) into the new web component to use it in the workspace.
#### Prerequisites
Capsulahub-UI: [Logger](https://github.com/capsulajs/capsulahub-ui/tree/develop/src/components/logger) 
## API
```
interface Event {
  timestamp: number;
  correlationId: string;
  type:  'request' | 'response';
  serviceName: string;
  methodName: string;
  data: any;
}

interface {
  logs$: Observable<Event>;
}
```
#### Design description

A clear and concise description of the design proposition.

- [ ] Is it backward compatible ?
- [ ] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Changes

Provide link to a PR or code snippet of old and new API.

#### Consideration
List of everything to consider before writing test cases.

- [ ] Does the suggested changes impact the current behaviour ?

- [ ] Does the suggested changes are specific to some devices/browsers/environments

- [ ] Does the suggested changes require to add new dependencies to the package ?

## Test cases
This PR includes the test cases : https://github.com/capsulajs/web-components/pull/3

## Ready for implementation
- [x] External dependencies have been resolved
- [x] API has been approved
- [x] Test cases have been prepared
- [x] Discussed with Product owner
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Manual QA
- [x] Documentation
- [ ] Release notes

**Comment by dmitriyslaym** [comment]
1) Where I should get correlationId?
2) Do we need to render request? Because in the design I see only one JSON object that can be opened, and as I understood it's a request but logger Event event also have request what to do with request?
3) In the design, we have green/red arrows and in which case we should show them instead of the default color?

**Comment by 95kach** [comment]
1. Invoker.
2. No.
3. According to the event type.

**Comment by stephanebenayoun** [comment]
Documentation is missing (at least have a md file in Logger package)
